version: '3'
services:
  web:
    build: './php/'
    #image: php:7.4-apache
    ports:
      - "8080:80"
        #volumes:
    volumes:
      - image-data:/var/www/html/uploads
      - /dev/bus/usb:/dev/bus/usb  # Agrega esta línea para acceder al bus USB desde el contenedor
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: my-phpmyadmin
     restart: always
     ports:
       - 8081:80
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: mypassword

volumes:
  db-data:
  image-data:

